[build]
command = "pnpm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "20"

[[redirects]]
from = "/.well-known/*"
status = 200
to = "/.well-known/:splat"

[[redirects]]
from = "/zh"
status = 200
to = "/zh/index.html"

[[redirects]]
from = "/zh/*"
status = 200
to = "/zh/index.html"

[[redirects]]
from = "/jp"
status = 200
to = "/jp/index.html"

[[redirects]]
from = "/jp/*"
status = 200
to = "/jp/index.html"

[[redirects]]
from = "/*"
status = 200
to = "/index.html"
