/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/data-loaders/art-gallery/': RouteRecordInfo<'/data-loaders/art-gallery/', '/data-loaders/art-gallery', Record<never, never>, Record<never, never>>,
    '/data-loaders/art-gallery/artwork.[id]': RouteRecordInfo<'/data-loaders/art-gallery/artwork.[id]', '/data-loaders/art-gallery/artwork/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/data-loaders/art-gallery/search': RouteRecordInfo<'/data-loaders/art-gallery/search', '/data-loaders/art-gallery/search', Record<never, never>, Record<never, never>>,
    '/inconsistent-state/': RouteRecordInfo<'/inconsistent-state/', '/inconsistent-state', Record<never, never>, Record<never, never>>,
    '/inconsistent-state/profile.[id].client-side': RouteRecordInfo<'/inconsistent-state/profile.[id].client-side', '/inconsistent-state/profile/:id/client-side', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
